services:
  - type: web
    name: irrigacao-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: mysql+pymysql://usuario:senha@host/db_irrigacao
